/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package main;

import main.Barang;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author USER
 */
public class Form_Barang extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    /**
     * Creates new form Form_Barang
     */ 
    
    public Form_Barang() {
        initComponents(); 
        initializeTableModel();
        customizeTable();
    }
    
    private void initializeTableModel() {
        String[] columnNames = {"Nomor", "Kode Barang", "Nama Barang", "Satuan", "Harga", "Penambahan(+/-)", "Total Stok"};
        tableModel = new DefaultTableModel(columnNames, 0);
        TableDataBarang.setModel(tableModel);
             
        Object[] row1 = {"1", "1001", "Beras Rojo Lele 5Kg", "Kg", "70000", "10", "10"};
        Object[] row2 = {"2", "1002", "Beras Rojo Gabus 10Kg", "Kg", "1500000", "20", "20"};
        Object[] row3 = {"3", "1003", "Bawang Merah Jaken", "Kg", "40000", "15", "15"};
        Object[] row4 = {"4", "1004", "Bawang Merah Super", "Kg", "50000", "10", "10"};
        Object[] row5 = {"5", "1005", "Cabai Margorejo ", "Kg", "100000", "100", "100"};
        Object[] row6 = {"6", "1006", "Gula Aren Super", "Kg", "40000", "75", "75"};
        Object[] row7 = {"7", "1007", "Gula Aren Premium", "Kg", "50000", "15", "15"};
        Object[] row8 = {"8", "1008", "Gula Pasir Tayu", "Kg", "15000", "40", "40"};

        tableModel.addRow(row1);
        tableModel.addRow(row2);
        tableModel.addRow(row3);
        tableModel.addRow(row4);
        tableModel.addRow(row5);
        tableModel.addRow(row6);
        tableModel.addRow(row7);
        tableModel.addRow(row8);
        }
    
    private void addRowToTable(Object[] rowData) {
        tableModel.addRow(rowData);
    }   
    
    private void customizeTable() {
        // Mengatur renderer untuk kolom yang ingin diubah rata tengah
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Mengatur alignment teks pada kolom 1, 2, 4, 5, 6, dan 7 menjadi rata tengah secara penuh
        TableDataBarang.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        TableDataBarang.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        TableDataBarang.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        TableDataBarang.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        TableDataBarang.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        
        // Mengatur alignment teks pada setiap kolom menjadi rata tengah secara penuh
        for (int i = 0; i < TableDataBarang.getColumnModel().getColumnCount(); i++) {
            TableDataBarang.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Mengatur alignment teks pada judul kolom menjadi rata tengah
        JTableHeader tableHeader = TableDataBarang.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) tableHeader.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);

        // Mengatur alignment teks pada kolom ke-5 (indeks kolom 4) menjadi rata kanan
        TableDataBarang.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);

        // Mengatur alignment teks pada kolom ke-3 (indeks kolom 2) menjadi rata kanan
        TableDataBarang.getColumnModel().getColumn(2).setCellRenderer(leftRenderer);
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDataBarang = new javax.swing.JTable();
        tambahBarang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        bt_kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_namaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_Satuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_jumlah = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setPreferredSize(new java.awt.Dimension(685, 517));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Barang");

        bt_tambah.setText("TAMBAH/KURANG");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setText("HAPUS");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        TableDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableDataBarang);

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(dataBarangLayout.createSequentialGroup()
                                .addComponent(bt_tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_hapus)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah)
                    .addComponent(bt_hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setPreferredSize(new java.awt.Dimension(685, 517));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Barang");

        bt_simpan.setText("SIMPAN");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setText("BATAL");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_kembali.setText("KEMBALI");
        bt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembaliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Kode Barang");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Satuan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Jumlah");

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_kodeBarang)
                    .addComponent(t_namaBarang)
                    .addComponent(t_Satuan)
                    .addComponent(t_jumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_harga)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(bt_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_kembali)))
                        .addGap(0, 420, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan)
                    .addComponent(bt_batal)
                    .addComponent(bt_kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembaliActionPerformed
        mainPanel.removeAll();
        mainPanel.add(dataBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_kembaliActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        String kodeBarang = t_kodeBarang.getText();
        String namaBarang = t_namaBarang.getText();
        String satuan = t_Satuan.getText();
        String harga = t_harga.getText();
        String jumlah = t_jumlah.getText();

        // Memeriksa apakah semua field telah diisi
        if (!kodeBarang.isEmpty() && !namaBarang.isEmpty() && !satuan.isEmpty() && !harga.isEmpty() && !jumlah.isEmpty()) {
        
            // Mendapatkan jumlah baris dalam jTable
            int rowCount = tableModel.getRowCount();

            // Menginisialisasi flag untuk menunjukkan apakah baris sudah ada atau tidak
            boolean rowExists = false;

            // Loop melalui setiap baris dalam jTable
            for (int i = 0; i < rowCount; i++) {
                // Mendapatkan nilai dari setiap kolom dalam baris
                String kodeBarangRow = tableModel.getValueAt(i, 1).toString();
                String namaBarangRow = tableModel.getValueAt(i, 2).toString();
                String satuanRow = tableModel.getValueAt(i, 3).toString();
                String hargaRow = tableModel.getValueAt(i, 4).toString();

                // Memeriksa apakah nilai-nilai tersebut sama dengan nilai-nilai yang diinputkan
                if (kodeBarang.equals(kodeBarangRow) &&
                        namaBarang.equals(namaBarangRow) &&
                        satuan.equals(satuanRow) &&
                        harga.equals(hargaRow)) {

                    // Jika ada baris yang sama, tambahkan stok baru ke stok lama pada baris tersebut
                    int stokLama = Integer.parseInt(tableModel.getValueAt(i, 6).toString());
                    int stokBaru = Integer.parseInt(jumlah);
                    int totalStok = stokLama + stokBaru;

                    tableModel.setValueAt(stokBaru, i, 5); // Mengubah nilai stok baru pada jTable
                    tableModel.setValueAt(totalStok, i, 6); // Mengubah nilai total stok pada jTable
                    rowExists = true; // Menandakan bahwa baris sudah ada
                    break; // Keluar dari loop karena sudah ditemukan baris yang sama
                }
            }
            // Jika baris tidak ditemukan, tambahkan baris baru dengan stok 1
            if (!rowExists) {
                Object[] rowData = {rowCount + 1, kodeBarang, namaBarang, satuan, harga, jumlah, jumlah};
                addRowToTable(rowData);
                JOptionPane.showMessageDialog(null, "Penambahan berhasil!");
            }
        }
        else {
            // Tampilkan pesan untuk melengkapi yang belum diisi
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua field terlebih dahulu.");
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin membatalkan dan menghapus?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION) {
                t_kodeBarang.setText("");
                t_namaBarang.setText("");
                t_Satuan.setText("");
                t_harga.setText("");
                t_jumlah.setText("");
            }
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // Mendapatkan indeks baris yang dipilih
        int selectedRow = TableDataBarang.getSelectedRow();

        // Memeriksa apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            // Konfirmasi penghapusan baris
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus baris ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Menghapus baris dari tabel
                tableModel.removeRow(selectedRow);
            }
        }
    }//GEN-LAST:event_bt_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDataBarang;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_kembali;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_Satuan;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_jumlah;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JPanel tambahBarang;
    // End of variables declaration//GEN-END:variables
}
